function [feature,label] = matrix2vector(matrix)
label = IsPPT(matrix);
feature = [matrix(1,1) matrix(2,2) matrix(3,3) ...
    real(matrix(1,2)) imag(matrix(1,2)) real(matrix(1,3)) imag(matrix(1,3)) real(matrix(1,4)) imag(matrix(1,4)) ...
    real(matrix(2,3)) imag(matrix(2,3)) real(matrix(2,4)) imag(matrix(2,4)) ...
    real(matrix(3,4)) imag(matrix(3,4)) ...
    ];
end

